name: Pull Request CI

on:
  pull_request:
    branches:
      - thor-upstream

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/test.yaml